baseURL = "https://moment-0204.github.io/hugosamplesite"
languageCode = "ja-jp"
theme = "SimpleIntro"
title = "SAMPLE"
publishDir = "docs"
canonifurls = true

[params]
    mainbg = "https://picsum.photos/1920/1080"
    mainTitle = "サンプルページ"
    mainText = "Hugoを用いてホームページを作る例"

[menus]
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "#about"
    [[menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "#projects"
    [[menu.main]]
        identifier = "skills"
        name = "Skills"
        url = "#skills"